language: go
go: 1.11.x

install:
- make prereqs
- make deps

script:
- make test
- make copyright
- git diff --exit-code
- git diff --cached --exit-code
- make crossbuild
- make docker-build

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
  - 'TRAVIS_COMMIT_SHORT="${TRAVIS_COMMIT:0:7}"'
  - 'GOBUILDFLAGS="-x"'

deploy:
  provider: script
  script: bin/docker-push
  # we don't need this for docker, but the artifacts push does
  skip_cleanup: true
  on:
    # push all non-PR builds to Docker Hub
    all_branches: true
    condition: "$TRAVIS_PULL_REQUEST == false"

addons:
  artifacts:
    paths:
    - "./build/linux/amd64/collectd-vsphere"
    - "./build/darwin/amd64/collectd-vsphere"
    target_paths:
    - travis-ci/collectd-vsphere/$TRAVIS_BRANCH
    - travis-ci/collectd-vsphere/$TRAVIS_COMMIT
    - travis-ci/collectd-vsphere/$TRAVIS_COMMIT_SHORT
