language: go
go: 1.7.5
sudo: false
install:
- make prereqs
- make deps
script:
- make test
- make copyright
- git diff --exit-code
- git diff --cached --exit-code
- make crossbuild

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
  - 'TRAVIS_COMMIT_SHORT="${TRAVIS_COMMIT:0:7}"'
  - 'GOBUILDFLAGS="-x"'

addons:
  artifacts:
    paths:
    - "./build/linux/amd64/collectd-vsphere"
    - "./build/darwin/amd64/collectd-vsphere"
    target_paths:
    - travis-ci/collectd-vsphere/$TRAVIS_BRANCH
    - travis-ci/collectd-vsphere/$TRAVIS_COMMIT
    - travis-ci/collectd-vsphere/$TRAVIS_COMMIT_SHORT
